// Generated by CoffeeScript 1.3.3
var host, http, port;

http = require("http");

host = process.env.VCAP_APP_HOST || "127.0.0.1";

port = process.env.VCAP_APP_PORT || 1337;

http.createServer(function(req, res) {
  var env, env_keys, key, _i, _len;
  res.writeHead(200, {
    "Content-Type": "text/html"
  });
  res.write("<title>Stackato environment variables</title>");
  res.write("<h1>Stackato environment variables</h1><hr/>");
  res.write("<table>");
  env_keys = [];
  for (key in process.env) {
    env_keys.push(key);
  }
  env_keys.sort();
  for (_i = 0, _len = env_keys.length; _i < _len; _i++) {
    env = env_keys[_i];
    res.write("<tr>\n  <td style=\"border-style: solid; \n             border-color: #034569;\n             background-color: #9FB6C3;\n             text-align: right;\n             vertical-align: top;\n             padding: 4px 1em;\">\n    <b>" + env + "</b>\n  </td>\n  <td>\n    <tt style=\"padding-left: 4px\">" + process.env[env] + "</tt>\n  </td>\n</tr>");
  }
  res.write("</table>");
  return res.end();
}).listen(port, host);

console.log("Server running at " + host + ":" + port);
